- name: Common tasks
  ansible.builtin.include_tasks: reachable.yaml
- name: Update
  ansible.builtin.include_tasks: update.yaml
- name: Common
  ansible.builtin.include_tasks: common.yaml
- name: User setup
  ansible.builtin.include_tasks: users.yaml
- name: postgres setup
  when: "'postgresql' in group_names"
  ansible.builtin.include_tasks: postgres_install.yaml
- name: seaweedfs setup
  when: "'seaweedfs' in group_names"
  ansible.builtin.include_tasks: seaweedfs_install.yaml
- name: RPM setup
  when: rpm_source == "airgapped"
  ansible.builtin.include_tasks: rpms_airgap.yaml
- name: RPM setup
  when: rpm_source != "airgapped"
  ansible.builtin.include_tasks: rpms_internet.yaml
- name: Shared Store setup
  when: shared_store_ip is defined
  ansible.builtin.include_tasks: sharedstore.yaml
- name: Create CA for selfsigned
  when: "ca_certs == 'selfsigned'"
  ansible.builtin.include_tasks: createca.yaml
  run_once: true
- name: Hub install
  ansible.builtin.include_tasks: hub_install.yaml
  when: "'hub' in group_names"
- name: Worker install
  ansible.builtin.include_tasks: worker_install.yaml
  when: "'workers' in group_names"
